---@class GNUI.Visual
---@field box GNUI.Box?
---@field init fun(self:GNUI.Visual,draw:GNUI.DrawBackend)
---@field update fun(self:GNUI.Visual,draw:GNUI.DrawBackend)
---@field free fun(self:GNUI.Visual,draw:GNUI.DrawBackend)